export const Lang = {
  en: {
    FEELTHEFLOW: "FEEL THE FLOW",
    heroSubTitle: "Next-Generation Streaming Application",
    heroText:
      "Redefining simplicity with a clean and seamless experience that works with complete efficiency. No clutter. No distractions. Just smart, <span style='font-weight:bold; color:#00bbff;'>fast performance powered by AI</span>.",
    ManagePlaylistTitle: "Manage Playlist",
    LoginPlaylist: "Login to add your playlist",
    Login: "Login",
    home: "Home",
    WhoWeAre: "Who We Are",
    vision: "Vision",
    howitworks: "How It Works",
    contact: "Contact",
    reseller: "Reseller",
    WishTvWebsite:
      "Our platform is the hub for entertainment solutions, boasting an extensive collection of streaming technologies and thoughtfully curated content.",
    WishTvDevice: "Watch Nova TV with these compatible streaming devices",
    ActivateDeviceOne: "Activate Devices",
    SwitchMac: "Switch Mac",
    ParentPin: "Parent Pin",
    AccountDetails: "Account Details",
    Logout: "Logout",
    WishTvAboutOne:
      "Nova TV is the most advanced and user-friendly TV media player.",
    WishTvAboutTwo:
      "With Nova TV, you will enjoy your favorite media on your smart TV.",
    MobileVersion: "Mobile version of",
    Available: "is available",
    wishtvAppAboutThree:
      "Available for Android on Play Store and iOS on App Store.",
    FAQsTitle: "Frequently Asked Questions",
    answerOne: "Does Nova TV contain any channels? Where can I get a playlist?",
    questionOne:
      "No, Nova TV application does not include any channels and no information will be provided about where you can get channels or channel packages. Also, application developers are not responsible for the content uploaded to Wish TV.",
    answerTwo: "How can I become a certified Wish TV provider?",
    questionTwo:
      "You can apply on the Wish TV platform or contact the support team for more information on becoming a certified provider.",
    answerThree: "How can I become a certified Wish TV provider?",
    questionThree:
      "If you experience a loading screen that never finishes, please restart the app or check your internet connection.",
    answerFour: "How can I use Nova TV?",
    questionFour:
      "Nova TV is simple to use. Download the app, log in with your credentials, and start enjoying your favorite media.",
    answerFive: "Having trouble finding our app in stores?",
    questionFive:
      "If you're having trouble finding our app, please ensure you're searching in the correct store for your device's OS (Android or iOS).",
    answerSix:
      "My MAC address has changed after I switched to another connection type.",
    questionSix:
      "If your MAC address changed after switching connection types, you might need to contact support for assistance in updating your credentials.",
    SendMessage: "Send Us a Message",
    ContactUs: "Contact Us",
    FullName: "Full Name",
    Email: "Email",
    Subject: "Subject",
    YourMessage: "Type Your message...",
    SendMessageButton: "Send Message",
    About: "About",
    aboutDesc:
      "Nova TV is an Player app that allows you to watch high-quality content on all devices, whether it's your TV, mobile, or Android box, regardless of your internet speed",
    PoliciesConditions: "Policies & Conditions",
    TermsConditions: "Terms & Conditions",
    PrivacyPolicy: "Privacy Policy",
    footer: "Copyright © 2025 Nova TV",
    AddPlaylist: "Add Playlist",
    LoadingPlaylists: "Loading playlists...",
    Playlist: "Playlist",
    Actions: "Actions",
    ActivateDevice: "Activate Device",
    Price: "Price",
    PaymentMethod: "Payment method",
    noteOne: "NOTE",
    noteDesc:
      "Nova TV does not provide content and is purely a media player. To use Wish TV, you must upload your own playlist. If you don’t have a playlist, you cannot use the Wish Player. In this case, do not pay. Also, we do not allow activation for users who do not have a playlist.",
    SwitchDevice: "Switch Device MAC",
    MaxLength: "Max length",
    newMacAddress: "New MAC Address",
    transferMacAddress:
      "Transfer your activation and playlists to another device MAC Address",
    noteTwo: "NOTE",
    noteDescTwo:
      "Your device login information, playlists, and activation period shall be transferred to this new device MAC address. Your old MAC address device will no longer be attached to this account.",
    Save: "Save",
    parentPinTitle: "Parent Pin",
    resetParentPIN: "Reset Parent PIN",
    newParentPin: "New Parent Pin",
    noteThree: "NOTE",
    noteDescThree:
      "If you forgot your parent pin in the app, you can change the parent pin here.",
    AccountDetailsTitle: "Account Details",
    Status: "Status",
    CreationDate: "Creation Date",
    ExpirationDate: "Expiration Date",
    AddPlaylistTitle: "Add Playlist",
    EditPlaylistTitle: "Edit Playlist",
    PlaylistName: "Playlist Name",
    EnterPlaylistName: "Enter Playlist Name",
    PlaylistURL: "Playlist URL",
    EnterPlaylistURL: "Enter Playlist URL",
    ProtectedPlaylist: "Protected Playlist",
    noteFour: "NOTE",
    noteDescFour:
      "Protected playlists will not be viewed or modified without entering a PIN.",
    Password: "Password",
    EnterPassword: "Enter Password",
    Cancel: "Cancel",
    Saving: "Saving...",
    UpdatePlaylist: "Update Playlist",
    ErrorMessageOne: "An error occurred",
    ErrorMessageTwo: "Playlist URL is required",
    ErrorMessageThree: "Password is required for protected playlists",
    EditErrorMessageOne: "Failed to update playlist",
    EditErrorMessageTwo: "Error updating playlist",
    EditErrorMessageThree: "An error occurred while updating the playlist",
    SaveChanges: "Save Changes",
    AccountDetailstTitle: "Account Details",
    AddPlaylistOne: "Add Playlist",
    AddPlaylistTwo: "Add Playlist",
    Enterplaylistname: "Enter playlist Name",
    EnterplaylistURL: "Enter Playlist URL",
    Enterpassword: "Enter password",
    EditPlaylist: "Edit Playlist",
    PlaylistNameOne: "Playlist Name",
    PlaylistURLOne: "Playlist URL",
    PasswordOne: "Password",
    EnterpasswordOne: "Enter password",
    wishtvAboutone:
      "Nova TV is the most advanced and user-friendly TV media player.",
    wishtvAboutTwo:
      "With Nova TV, you will enjoy your favorite media on your smart TV.",
    // Footer translations
    footerDescription:
      "Next-generation streaming application redefining simplicity.",
    quickLinks: "Quick Links",
    whoWeAre: "Who We Are",
    features: "Features",
    howItWorks: "How It Works",
    becomeReseller: "Become a Reseller",
    support: "Support",
    contactUs: "Contact Us",
    manageDevices: "Manage Devices",
    faq: "FAQ",
    documentation: "Documentation",
    legal: "Legal",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    cookiePolicy: "Cookie Policy",
    copyright: "© 2024 Intertament. All rights reserved.",
    poweredBy: "Powered by Servo IT",
    // WhatsApp and Login form translations
    whatsappAccountName: "Servo Player",
    whatsappStatusMessage: "Typically replies within 1 hour",
    whatsappChatMessage: "Hello! How can we help you?",
    whatsappPlaceholder: "Contact us",
    loginDescription: "Enter your MAC Address & Device Key to continue",
    macAddressLabel: "MAC Address",
    macAddressPlaceholder: "Enter your MAC Address",
    deviceKeyLabel: "Device Key",
    deviceKeyPlaceholder: "Enter your Device Key",
    loginInfoText:
      "Your MAC Address and Device Key can be found in your app settings. If you need help, please contact support.",
    loginFailedMessage: "Login failed. Please try again.",
    // WhoWeAre component translations
    whoWeAreTitle: "Who We Are",
    whoWeAreText1: "We are",
    whoWeAreText2: "Intertament",
    whoWeAreText3:
      ", a company that offers a next-generation streaming application redefining simplicity.",
    whoWeAreText4:
      "Our platform focuses on what truly matters — a clean and seamless experience that works with complete efficiency.",
    whoWeAreText5: "No clutter. No distractions.",
    whoWeAreText6:
      "Just smart, fast performance powered by AI, along with business support and development tools for resellers and industry professionals.",
    // Vision component translations
    visionTitle: "Our Vision",
    visionText: "To become the most",
    visionTrusted: "trusted",
    visionUserFriendly: "user-friendly",
    visionFutureReady: "and future-ready",
    visionTextEnd: "platform in the world.",
    visionTrustedLabel: "Trusted",
    visionUserFriendlyLabel: "User-Friendly",
    visionFutureReadyLabel: "Future-Ready",
    // Mission component translations
    missionTitle: "Our Mission",
    missionText1: "To provide users with a",
    missionText1Highlight: "fluid, seamless, and innovative",
    missionText1End: "streaming experience",
    missionText2: "To offer resellers an",
    missionText2Highlight: "efficient management platform",
    missionText2End: "and growth support",
    // Values component translations
    valuesTitle: "Our Values",
    valuesSubtitle: "The principles that guide everything we do",
    valuesSimplicity: "Simplicity",
    valuesSimplicityDesc: "Clean, intuitive design that anyone can use",
    valuesTrust: "Trust",
    valuesTrustDesc: "Reliable and secure platform you can depend on",
    valuesInnovation: "Innovation",
    valuesInnovationDesc: "Cutting-edge AI technology for the future",
    valuesComfort: "Comfort",
    valuesComfortDesc: "Seamless experience designed for your ease",
    valuesTransparency: "Transparency",
    valuesTransparencyDesc: "Open and honest in everything we do",
    valuesSupport: "Support",
    valuesSupportDesc: "24/7 assistance whenever you need us",
    // Features component translations
    featuresTitle: "Player Features",
    featuresSubtitle:
      "Everything you need for the perfect streaming experience",
    featuresModernDesign: "Modern & Clean Design",
    featuresModernDesignDesc:
      "A lightweight, eye-friendly interface that puts content first",
    featuresInstantAccess: "Instant Access",
    featuresInstantAccessDesc:
      "Enter the server and start watching immediately",
    featuresSecureStable: "Secure & Stable",
    featuresSecureStableDesc:
      "Built for maximum performance, protection, and speed",
    featuresInteractiveIntelligence: "Interactive Intelligence",
    featuresInteractiveIntelligenceDesc:
      "Learns from your usage to recommend the best AI-powered content",
    featuresSmartSearch: "Smart Search Engine",
    featuresSmartSearchDesc:
      "Fast, intuitive, and intelligent content discovery",
    // HowItWorks component translations
    howItWorksTitle: "How It Works",
    howItWorksSubtitle: "Get started in just 3 simple steps",
    howItWorksStep1Title: "Download & Install",
    howItWorksStep1Desc:
      "Search for Servo Player on your device's store and install it.",
    howItWorksStep1Note: "Currently available on Samsung and LG",
    howItWorksStep1ComingSoon:
      "Coming soon to Android TV, iOS, Toku, Windows, and Apple TV",
    howItWorksStep2Title: "Enter Your Credentials",
    howItWorksStep2Desc:
      "Enter your server URL or activation code via the website.",
    howItWorksStep3Title: "Enjoy Streaming",
    howItWorksStep3Desc:
      "Let our AI enhance your experience and enjoy smooth streaming.",
    howItWorksAvailablePlatforms: "Available Platforms",
    howItWorksComingSoon: "Coming Soon",
    // WhyChooseUs component translations
    whyChooseUsTitle: "Why Choose to Become a Reseller With Us",
    whyChooseUsSubtitle:
      "Partner with Servo today and Enjoy the streaming experience of the future",
    whyChooseUsFullControl: "Full Control",
    whyChooseUsFullControlDesc:
      "Full Control over your clients through a professional dashboard",
    whyChooseUsSupport: "24/7 Technical Support",
    whyChooseUsSupportDesc: "Round-the-clock assistance whenever you need it",
    whyChooseUsPricing: "Competitive Pricing",
    whyChooseUsPricingDesc: "Excellent value for money with wholesale rates",
    whyChooseUsOffers: "Exclusive Offers",
    whyChooseUsOffersDesc: "Special packages and deals for our resellers",
    whyChooseUsTrusted: "Trusted Platform",
    whyChooseUsTrustedDesc:
      "A Trusted, Modern Platform Powered by AI — Loved by customers",
    whyChooseUsManagement: "Centralized Management",
    whyChooseUsManagementDesc:
      "Control all users, devices, and subscriptions in one place",
    whyChooseUsPerformance: "Reliable Performance",
    whyChooseUsPerformanceDesc:
      "Say goodbye to downtime and instability — Servo delivers consistent, smooth performance 24/7",
    whyChooseUsPartnership:
      "👉 Partner with Servo today and give your customers the streaming experience of the future.",
    whyChooseUsStartPartnership: "Start Your Partnership",
    // Contact component translations
    contactTitle: "Contact Us",
    contactSubtitle:
      "For more information or business inquiries, please don't hesitate to reach out",
    contactGetInTouch: "Get in Touch",
    contactEmail: "Email",
    contactSupport: "Support",
    contactSupportAvailable: "24/7 Available",
    contactResponseTime: "Response Time",
    contactResponseTimeValue: "Within 24 hours",
    contactFollowUs: "Follow Us",
    contactName: "Name",
    contactNamePlaceholder: "Your name",
    contactEmailPlaceholder: "your@email.com",
    contactSubject: "Subject",
    contactSubjectPlaceholder: "How can we help?",
    contactMessage: "Message",
    contactMessagePlaceholder: "Your message...",
    contactSendMessage: "Send Message",
  },
  ar: {
    FEELTHEFLOW: "أشعُر بالحركة",
    LoginPlaylist: "قم بتسجيل الدخول لإضافة قائمة التشغيل الخاصة بك",
    Login: "تسجيل الدخول",
    heroSubTitle: "تطبيق بث من الجيل القادم",
    heroText:
      "نعيد تعريف البساطة من خلال تجربة نظيفة وسلسة تعمل بكفاءة تامة. بدون فوضى، بدون تشتيت. فقط أداء ذكي وسريع مدعوم بالذكاء الاصطناعي.",
    home: "الرئيسية",
    WhoWeAre: "من نحن",
    vision: "الرؤية",
    features: "المميزات",
    howitworks: "كيف يعمل",
    reseller: "بائع",
    contact: "تواصل معنا",
    WishTvWebsite:
      "منصتنا هي المركز لحلول الترفيه، وتتميز بمجموعة واسعة من تقنيات البث والمحتوى المختار بعناية.",
    WishTvDevice: "شاهد خدمات تطبيقنا باستخدام اجهزة البث المتوافقه",
    ManagePlaylistTitle: "إدارة قائمة التشغيل",
    ActivateDeviceOne: "تفعيل الأجهزة",
    SwitchMac: "تبديل الماك",
    ParentPin: "رمز التحكم العائلى",
    AccountDetails: "تفاصيل الحساب",
    Logout: "تسجيل الخروج",
    wishtvAboutone:
      "تطبيقنا هو مشغل الوسائط التلفزيونية الأكثر تقدمًا وسهولة في الاستخدام.",
    wishtvAboutTwo:
      "مع تطبيقنا، سوف تستمتع بالوسائط المفضلة لديك على التلفزيون الذكي الخاص بك.",
    MobileVersion: "النسخة المحمولة من",
    available: "متاحه",
    wishtvAppAboutThree:
      "متاح لنظام الاندرويد على بلاى ستور ولاجهزة الايفون على اب ستور",
    faqsTitle: "الأسئلة الشائعة",
    answerOne:
      "هل يحتوي تطبيقنا على أي قنوات؟ أين يمكنني الحصول على قائمة تشغيل؟",
    questionOne:
      "لا، لا يتضمن تطبيقنا أي قنوات ولن يتم تقديم أي معلومات حول المكان الذي يمكنك الحصول فيه على القنوات أو باقات القنوات. كما أن مطوري التطبيق غير مسؤولين عن المحتوى الذي يتم تحميله على Wish TV.",
    answerTwo: "كيف يمكنني أن أصبح مقدم خدمة ويش تى فى معتمدًا؟",
    questionTwo:
      "يمكنك التقديم على منصة ويش تى فى أو التواصل مع فريق الدعم للحصول على مزيد من المعلومات حول كيفية أن تصبح مقدم خدمة معتمدًا.",
    answerThree: "هل لديك شاشة تحميل لا تنتهي؟",
    questionThree:
      "إذا واجهت شاشة تحميل لا تنتهي أبدًا، فيرجى إعادة تشغيل التطبيق أو التحقق من اتصالك بالإنترنت.",
    answerFour: "كيف يمكنني استخدام نوفا تى فى؟",
    questionFour:
      "يعد استخدام تطبيقنا سهلاً. قم بتنزيل التطبيق، وسجّل الدخول باستخدام بيانات الاعتماد الخاصة بك، وابدأ في الاستمتاع بالوسائط المفضلة لديك.",
    answerFive: "هل تواجه مشكلة في العثور على تطبيقنا في المتاجر؟",
    questionFive:
      "إذا كنت تواجه مشكلة في العثور على تطبيقنا، فيرجى التأكد من أنك تبحث في المتجر الصحيح لنظام التشغيل الخاص بجهازك (اندرويد أو ايفون).",
    answerSix:
      "لقد تغير عنوان ماك الخاص بي بعد أن قمت بالتبديل إلى نوع اتصال آخر.",
    questionSix:
      "إذا تغير عنوان ماك الخاص بك بعد تبديل أنواع الاتصال، فقد تحتاج إلى الاتصال بالدعم للحصول على المساعدة في تحديث بيانات الاعتماد الخاصة بك.",
    SendMessage: "أرسل لنا رسالة",
    ContactUs: "تواصل معنا",
    FullName: "الاسم بالكامل",
    Email: "البريد الالكترونى",
    Subject: "الموضوع",
    YourMessage: "اكتب رسالتك هنا",
    SendMessageButton: "ارسل رسالة",
    About: "من نحن",
    aboutDesc:
      "Nova TV هو تطبيق مشغل يسمح لك بمشاهدة محتوى عالي الجودة على جميع الأجهزة، سواء كان جهاز التلفزيون أو الهاتف المحمول أو جهاز Android، بغض النظر عن سرعة الإنترنت لديك`",
    PoliciesConditions: "السياسات والشروط",
    TermsConditions: "الشروط والأحكام",
    PrivacyPolicy: "سياسة الخصوصية",
    footer: "جميع الحقوق محفوظة © 2025 قناة نوفا تي في",
    AddPlaylist: "إضافة قائمة التشغيل",
    LoadingPlaylists: "جاري تحميل قوائم التشغيل...",
    Playlist: "قائمة التشغيل",
    Actions: "الإجراءات",
    ActivateDevice: "تفعيل الجهاز",
    Price: "السعر",
    PaymentMethod: "طريقة الدفع",
    noteOne: "ملحوظة",
    noteDesc:
      "لا يوفر تطبيقنا أي محتوى، وهو عبارة عن مشغل وسائط فقط. لاستخدام تطبيقنا، يتعين عليك تحميل قائمة التشغيل الخاصة بك. إذا لم يكن لديك قائمة تشغيل، فلن تتمكن من استخدام مشغل ويش بعد الآن، لذا في هذه الحالة لا تدفع. كما أننا لا نسمح بالتنشيط للمستخدمين الذين ليس لديهم قوائم تشغيل.",
    SwitchDevice: "تبديل جهاز MAC",
    MaxLength: "الحد الاقصى",
    newMacAddress: "عنوان MAC الجديد",
    transferMacAddress: "نقل التنشيط وقوائم التشغيل إلى عنوان MAC لجهاز آخر",
    noteTwo: "ملحوظة",
    noteDescTwo:
      "سيتم نقل معلومات تسجيل الدخول الخاصة بجهازك وقوائم التشغيل وفترة التنشيط إلى عنوان MAC الجديد الخاص بهذا الجهاز. لن يكون عنوان MAC القديم الخاص بك مرتبطًا بهذا الحساب بعد الآن.",
    Save: "حفظ",
    parentPinTitle: "رمز التحكم العائلى",
    resetParentPIN: "إعادة تعيين رقم التعريف الشخصي للوالدين",
    newParentPin: "رمز الجديد التحكم العائلى",
    noteThree: "ملحوظة",
    noteDescThree:
      "إذا نسيت رمز التعريف الشخصي الأساسي الخاص بك في التطبيق، فيمكنك تغيير رمز التعريف الشخصي الأساسي هنا.",
    AccountDetailsTitle: "تفاصيل الحساب",
    Status: "حالة",
    CreationDate: "تاريخ الأنشاء",
    ExpirationDate: "تاريخ الأنتهاء",
    AddPlaylistOne: "إضافة قائمة التشغيل",
    AddPlaylistTwo: "إضافة قائمة التشغيل",
    EditPlaylistOne: "تعديل قائمة التشغيل",
    PlaylistName: "اسم قائمة التشغيل",
    EnterPlaylistName: "أدخل اسم قائمة التشغيل",
    PlaylistURL: "رابط قائمة التشغيل",
    EnterPlaylistURL: "أدخل عنوان URL لقائمة التشغيل",
    ProtectedPlaylist: "قائمة التشغيل المحمية",
    noteFour: "ملحوظة",
    noteDescFour:
      "لن يتم عرض قوائم التشغيل المحمية أو تعديلها دون إدخال رقم التعريف الشخصي (PIN)",
    Password: "كلمة المرور",
    EnterPassword: "ادخل كلمة المرور",
    Cancel: "إلغاء",
    Saving: "جارى التعديل...",
    UpdatePlaylist: "تحديث قائمة التشغيل",
    errorMessageOne: "اسم قائمة التشغيل مطلوب",
    errorMessageTwo: "مطلوب عنوان URL لقائمة التشغيل",
    errorMessageThree: "مطلوب كلمة مرور لقوائم التشغيل المحمية",
    EditErrorMessageOne: "فشل في تحديث قائمة التشغيل",
    EditErrorMessageTwo: "خطأ في تحديث قائمة التشغيل:",
    EditErrorMessageThree: "حدث خطأ أثناء تحديث قائمة التشغيل",
    EditPlaylist: "تعديل قائمة التشغيل",
    PlaylistNameOne: "اسم قائمة التشغيل",
    PlaylistURLOne: "رابط قائمة التشغيل",
    PasswordOne: "كلمة المرور",
    EnterPasswordOne: "ادخل كلمة المرور",
    SaveChanges: "حفظ التغيرات",
    AccountDetailstTitle: "تفاصيل الحساب",
    Enterplaylistname: "أدخل اسم قائمة التشغيل",
    EnterplaylistURL: "أدخل عنوان URL لقائمة التشغيل",
    Enterpassword: "ادخل كلمة المرور",
    // Footer translations
    footerDescription: "تطبيق البث من الجيل التالي يعيد تعريف البساطة.",
    quickLinks: "روابط سريعة",
    whoWeAre: "من نحن",
    howItWorks: "كيف يعمل",
    becomeReseller: "كن موزعًا",
    support: "الدعم",
    contactUs: "تواصل معنا",
    manageDevices: "إدارة الأجهزة",
    faq: "الأسئلة الشائعة",
    documentation: "الوثائق",
    legal: "قانوني",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    cookiePolicy: "سياسة ملفات تعريف الارتباط",
    copyright: "© 2024 إنترتامنت. جميع الحقوق محفوظة.",
    poweredBy: "مدعوم من Servo IT",
    // WhatsApp and Login form translations
    whatsappAccountName: "سيرفو بلاير",
    whatsappStatusMessage: "عادة ما يرد خلال ساعة واحدة",
    whatsappChatMessage: "مرحباً! كيف يمكننا مساعدتك؟",
    whatsappPlaceholder: "تواصل معنا",
    loginDescription: "أدخل عنوان MAC ومفتاح الجهاز للمتابعة",
    macAddressLabel: "عنوان MAC",
    macAddressPlaceholder: "أدخل عنوان MAC الخاص بك",
    deviceKeyLabel: "مفتاح الجهاز",
    deviceKeyPlaceholder: "أدخل مفتاح الجهاز",
    loginInfoText:
      "يمكن العثور على عنوان MAC ومفتاح الجهاز في إعدادات التطبيق. إذا كنت بحاجة إلى مساعدة، يرجى الاتصال بالدعم.",
    loginFailedMessage: "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.",
    // WhoWeAre component translations
    whoWeAreTitle: "من نحن",
    whoWeAreText1: "نحن",
    whoWeAreText2: "إنترتامنت",
    whoWeAreText3: "، شركة تقدم تطبيق بث من الجيل التالي يعيد تعريف البساطة.",
    whoWeAreText4:
      "تركز منصتنا على ما يهم حقاً — تجربة نظيفة وسلسة تعمل بكفاءة كاملة.",
    whoWeAreText5: "لا فوضى. لا إلهاءات.",
    whoWeAreText6:
      "فقط أداء ذكي وسريع مدعوم بالذكاء الاصطناعي، مع دعم الأعمال وأدوات التطوير للموزعين والمهنيين في الصناعة.",
    // Vision component translations
    visionTitle: "رؤيتنا",
    visionText: "أن نصبح أكثر",
    visionTrusted: "موثوقية",
    visionUserFriendly: "سهولة في الاستخدام",
    visionFutureReady: "جاهزية للمستقبل",
    visionTextEnd: "منصة في العالم.",
    visionTrustedLabel: "موثوق",
    visionUserFriendlyLabel: "سهل الاستخدام",
    visionFutureReadyLabel: "جاهز للمستقبل",
    // Mission component translations
    missionTitle: "مهمتنا",
    missionText1: "تزويد المستخدمين بتجربة بث",
    missionText1Highlight: "سلسة ومبتكرة",
    missionText1End: "ومتطورة",
    missionText2: "تزويد الموزعين",
    missionText2Highlight: "بمنصة إدارة فعالة",
    missionText2End: "ودعم النمو",
    // Values component translations
    valuesTitle: "قيمنا",
    valuesSubtitle: "المبادئ التي توجه كل ما نقوم به",
    valuesSimplicity: "البساطة",
    valuesSimplicityDesc: "تصميم نظيف وبديهي يمكن لأي شخص استخدامه",
    valuesTrust: "الثقة",
    valuesTrustDesc: "منصة موثوقة وآمنة يمكنك الاعتماد عليها",
    valuesInnovation: "الابتكار",
    valuesInnovationDesc: "تقنية ذكاء اصطناعي متطورة للمستقبل",
    valuesComfort: "الراحة",
    valuesComfortDesc: "تجربة سلسة مصممة لراحتك",
    valuesTransparency: "الشفافية",
    valuesTransparencyDesc: "منفتحون وصادقون في كل ما نقوم به",
    valuesSupport: "الدعم",
    valuesSupportDesc:
      "مساعدة على مدار الساعة طوال أيام الأسبوع كلما احتجت إلينا",
    // Features component translations
    featuresTitle: "ميزات المشغل",
    featuresSubtitle: "كل ما تحتاجه لتجربة بث مثالية",
    featuresModernDesign: "تصميم حديث ونظيف",
    featuresModernDesignDesc: "واجهة خفيفة ومريحة للعين تضع المحتوى في المقدمة",
    featuresInstantAccess: "وصول فوري",
    featuresInstantAccessDesc: "ادخل الخادم وابدأ المشاهدة فوراً",
    featuresSecureStable: "آمن ومستقر",
    featuresSecureStableDesc: "مبني لأقصى أداء وحماية وسرعة",
    featuresInteractiveIntelligence: "ذكاء تفاعلي",
    featuresInteractiveIntelligenceDesc:
      "يتعلم من استخدامك ليقترح أفضل المحتوى المدعوم بالذكاء الاصطناعي",
    featuresSmartSearch: "محرك بحث ذكي",
    featuresSmartSearchDesc: "اكتشاف محتوى سريع وبديهي وذكي",
    // HowItWorks component translations
    howItWorksTitle: "كيف يعمل",
    howItWorksSubtitle: "ابدأ في 3 خطوات بسيطة فقط",
    howItWorksStep1Title: "تحميل وتثبيت",
    howItWorksStep1Desc: "ابحث عن سيرفو بلاير في متجر جهازك وقم بتثبيته.",
    howItWorksStep1Note: "متاح حالياً على سامسونج وإل جي",
    howItWorksStep1ComingSoon:
      "قريباً على أندرويد تي في، آي أو إس، توكو، ويندوز، وآبل تي في",
    howItWorksStep2Title: "أدخل بيانات الاعتماد",
    howItWorksStep2Desc: "أدخل رابط الخادم أو رمز التفعيل عبر الموقع.",
    howItWorksStep3Title: "استمتع بالبث",
    howItWorksStep3Desc: "دع ذكاءنا الاصطناعي يحسن تجربتك واستمتع ببث سلس.",
    howItWorksAvailablePlatforms: "المنصات المتاحة",
    howItWorksComingSoon: "قريباً",
    // WhyChooseUs component translations
    whyChooseUsTitle: "لماذا تختار أن تصبح موزعاً معنا",
    whyChooseUsSubtitle: "إشترك مع سيرفو اليوم وإحصل على تجربة البث المستقبلية",
    whyChooseUsFullControl: "تحكم كامل",
    whyChooseUsFullControlDesc: "تحكم كامل في عملائك من خلال لوحة تحكم مهنية",
    whyChooseUsSupport: "دعم فني على مدار الساعة",
    whyChooseUsSupportDesc: "مساعدة على مدار الساعة كلما احتجت إليها",
    whyChooseUsPricing: "أسعار تنافسية",
    whyChooseUsPricingDesc: "قيمة ممتازة مقابل المال مع أسعار الجملة",
    whyChooseUsOffers: "عروض حصرية",
    whyChooseUsOffersDesc: "باقات وعروض خاصة لموزعينا",
    whyChooseUsTrusted: "منصة موثوقة",
    whyChooseUsTrustedDesc:
      "منصة حديثة وموثوقة مدعومة بالذكاء الاصطناعي — محبوبة من العملاء",
    whyChooseUsManagement: "إدارة مركزية",
    whyChooseUsManagementDesc:
      "تحكم في جميع المستخدمين والأجهزة والاشتراكات في مكان واحد",
    whyChooseUsPerformance: "أداء موثوق",
    whyChooseUsPerformanceDesc:
      "وداعاً للتوقف وعدم الاستقرار — سيرفو يوفر أداءً ثابتاً وسلساً على مدار الساعة",
    whyChooseUsPartnership:
      "👉 إشترك مع سيرفو اليوم وإحصل على تجربة البث المستقبلية.",
    whyChooseUsStartPartnership: "ابدأ شراكتك",
    // Contact component translations
    contactTitle: "تواصل معنا",
    contactSubtitle:
      "لمزيد من المعلومات أو الاستفسارات التجارية، لا تتردد في التواصل معنا",
    contactGetInTouch: "تواصل معنا",
    contactEmail: "البريد الإلكتروني",
    contactSupport: "الدعم",
    contactSupportAvailable: "متاح على مدار الساعة",
    contactResponseTime: "وقت الاستجابة",
    contactResponseTimeValue: "خلال 24 ساعة",
    contactFollowUs: "تابعنا",
    contactName: "الاسم",
    contactNamePlaceholder: "اسمك",
    contactEmailPlaceholder: "بريدك@الإلكتروني.com",
    contactSubject: "الموضوع",
    contactSubjectPlaceholder: "كيف يمكننا المساعدة؟",
    contactMessage: "الرسالة",
    contactMessagePlaceholder: "رسالتك...",
    contactSendMessage: "إرسال الرسالة",
  },
  es: {
    FEELTHEFLOW: "SIENTE EL FLUJO",
    heroSubTitle: "Aplicación de transmisión de nueva generación",
    heroText:
      "Redefiniendo la simplicidad con una experiencia limpia y fluida que funciona con completa eficiencia. Sin desorden. Sin distracciones. Solo rendimiento inteligente y rápido impulsado por IA.",
    ManagePlaylistTitle: "Gestionar lista de reproducción",
    LoginPlaylist: "Inicia sesión para añadir tu lista de reproducción",
    Login: "Iniciar sesión",
    home: "Inicio",
    WhoWeAre: "Quiénes somos",
    vision: "Visión",
    features: "Características",
    howitworks: "Cómo funciona",
    contact: "Contacto",
    reseller: "Revendedor",
    WishTvWebsite:
      "Nuestra plataforma es el centro de soluciones de entretenimiento, con una amplia colección de tecnologías de streaming y contenido cuidadosamente seleccionado.",
    WishTvDevice:
      "Mira Nova TV con estos dispositivos de streaming compatibles",
    ActivateDeviceOne: "Activar dispositivos",
    SwitchMac: "Cambiar MAC",
    ParentPin: "PIN parental",
    AccountDetails: "Detalles de la cuenta",
    Logout: "Cerrar sesión",
    WishTvAboutOne:
      "Nova TV es el reproductor de medios para TV más avanzado y fácil de usar.",
    WishTvAboutTwo:
      "Con Nova TV, disfrutarás de tus medios favoritos en tu smart TV.",
    MobileVersion: "Versión móvil de",
    Available: "está disponible",
    wishtvAppAboutThree:
      "Disponible para Android en Play Store y para iOS en App Store.",
    FAQsTitle: "Preguntas frecuentes",
    answerOne:
      "¿Contiene Nova TV algún canal? ¿Dónde puedo obtener una lista de reproducción?",
    questionOne:
      "No, la aplicación Nova TV no incluye ningún canal y no se proporcionará información sobre dónde puedes obtener canales o paquetes de canales. Además, los desarrolladores de la aplicación no son responsables del contenido subido a Wish TV.",
    answerTwo: "¿Cómo puedo convertirme en proveedor certificado de Wish TV?",
    questionTwo:
      "Puedes solicitarlo en la plataforma Wish TV o contactar al equipo de soporte para más información sobre cómo convertirte en proveedor certificado.",
    answerThree: "¿Cómo puedo convertirme en proveedor certificado de Wish TV?",
    questionThree:
      "Si experimentas una pantalla de carga que nunca termina, por favor reinicia la app o comprueba tu conexión a internet.",
    answerFour: "¿Cómo puedo usar Nova TV?",
    questionFour:
      "Nova TV es simple de usar. Descarga la app, inicia sesión con tus credenciales y comienza a disfrutar de tus medios favoritos.",
    answerFive: "¿Tienes problemas para encontrar nuestra app en las tiendas?",
    questionFive:
      "Si tienes problemas para encontrar nuestra app, asegúrate de que estás buscando en la tienda correcta para el sistema operativo de tu dispositivo (Android o iOS).",
    answerSix:
      "Mi dirección MAC ha cambiado después de cambiar de tipo de conexión.",
    questionSix:
      "Si tu dirección MAC cambió después de cambiar el tipo de conexión, puede que necesites contactar al soporte para asistencia en la actualización de tus credenciales.",
    SendMessage: "Envíanos un mensaje",
    ContactUs: "Contáctanos",
    FullName: "Nombre completo",
    Email: "Correo electrónico",
    Subject: "Asunto",
    YourMessage: "Escribe tu mensaje...",
    SendMessageButton: "Enviar mensaje",
    About: "Acerca de",
    aboutDesc:
      "Nova TV es una aplicación reproductor que te permite ver contenido de alta calidad en todos los dispositivos, ya sea tu TV, móvil o caja Android, independientemente de la velocidad de internet que tengas.",
    PoliciesConditions: "Políticas y condiciones",
    TermsConditions: "Términos y condiciones",
    PrivacyPolicy: "Política de privacidad",
    footer: "Copyright © 2025 Nova TV",
    AddPlaylist: "Añadir lista de reproducción",
    LoadingPlaylists: "Cargando listas de reproducción…",
    Playlist: "Lista de reproducción",
    Actions: "Acciones",
    ActivateDevice: "Activar dispositivo",
    Price: "Precio",
    PaymentMethod: "Método de pago",
    noteOne: "NOTA",
    noteDesc:
      "Nova TV no proporciona contenido y es únicamente un reproductor de medios. Para usar Wish TV debes subir tu propia lista de reproducción. Si no tienes lista de reproducción, no puedes usar el reproductor Wish. En ese caso, no pagues. Tampoco permitimos activaciones para usuarios que no tengan lista de reproducción.",
    SwitchDevice: "Cambiar dispositivo MAC",
    MaxLength: "Longitud máxima",
    newMacAddress: "Nueva dirección MAC",
    transferMacAddress:
      "Transfiere tu activación y listas de reproducción a otra dirección MAC de dispositivo",
    noteTwo: "NOTA",
    noteDescTwo:
      "Tu información de inicio de sesión del dispositivo, listas de reproducción y periodo de activación serán transferidos a esta nueva dirección MAC del dispositivo. Tu dispositivo con la antigua dirección MAC ya no estará vinculado a esta cuenta.",
    Save: "Guardar",
    parentPinTitle: "PIN parental",
    resetParentPIN: "Restablecer PIN parental",
    newParentPin: "Nuevo PIN parental",
    noteThree: "NOTA",
    noteDescThree:
      "Si olvidaste tu PIN parental en la app, puedes cambiarlo aquí.",
    AccountDetailsTitle: "Detalles de la cuenta",
    Status: "Estado",
    CreationDate: "Fecha de creación",
    ExpirationDate: "Fecha de expiración",
    AddPlaylistTitle: "Añadir lista de reproducción",
    EditPlaylistTitle: "Editar lista de reproducción",
    PlaylistName: "Nombre de la lista de reproducción",
    EnterPlaylistName: "Introduce el nombre de la lista de reproducción",
    PlaylistURL: "URL de la lista de reproducción",
    EnterPlaylistURL: "Introduce la URL de la lista de reproducción",
    ProtectedPlaylist: "Lista de reproducción protegida",
    noteFour: "NOTA",
    noteDescFour:
      "Las listas de reproducción protegidas no podrán verse ni modificarse sin introducir un PIN.",
    Password: "Contraseña",
    EnterPassword: "Introduce la contraseña",
    Cancel: "Cancelar",
    Saving: "Guardando…",
    UpdatePlaylist: "Actualizar lista de reproducción",
    ErrorMessageOne: "Ocurrió un error",
    ErrorMessageTwo: "Se requiere la URL de la lista de reproducción",
    ErrorMessageThree: "Se requiere contraseña para listas protegidas",
    EditErrorMessageOne: "Error al actualizar la lista de reproducción",
    EditErrorMessageTwo: "Error al actualizar la lista de reproducción:",
    EditErrorMessageThree:
      "Se produjo un error mientras se actualizaba la lista de reproducción",
    SaveChanges: "Guardar cambios",
    AccountDetailstTitle: "Detalles de la cuenta",
    AddPlaylistOne: "Añadir lista de reproducción",
    AddPlaylistTwo: "Añadir lista de reproducción",
    Enterplaylistname: "Introduce el nombre de la lista de reproducción",
    EnterplaylistURL: "Introduce la URL de la lista de reproducción",
    Enterpassword: "Introduce la contraseña",
    EditPlaylist: "Editar lista de reproducción",
    PlaylistNameOne: "Nombre de la lista de reproducción",
    PlaylistURLOne: "URL de la lista de reproducción",
    PasswordOne: "Contraseña",
    EnterpasswordOne: "Introduce la contraseña",
    wishtvAboutone:
      "Nova TV es el reproductor de medios para TV más avanzado y fácil de usar.",
    wishtvAboutTwo:
      "Con Nova TV, disfrutarás de tus medios favoritos en tu smart TV.",
    footerDescription:
      "Aplicación de streaming de nueva generación que redefine la simplicidad.",
    quickLinks: "Enlaces rápidos",
    whoWeAre: "Quiénes somos",
    howItWorks: "Cómo funciona",
    becomeReseller: "Conviértete en revendedor",
    support: "Soporte",
    contactUs: "Contáctanos",
    manageDevices: "Gestionar dispositivos",
    faq: "Preguntas frecuentes",
    documentation: "Documentación",
    legal: "Legal",
    privacyPolicy: "Política de privacidad",
    termsOfService: "Términos del servicio",
    cookiePolicy: "Política de cookies",
    copyright: "© 2024 Intertament. Todos los derechos reservados.",
    poweredBy: "Desarrollado por Servo IT",
    whatsappAccountName: "Servo Player",
    whatsappStatusMessage: "Normalmente responde en 1 hora",
    whatsappChatMessage: "¡Hola! ¿Cómo podemos ayudarte?",
    whatsappPlaceholder: "Contáctanos",
    loginDescription:
      "Introduce tu dirección MAC y clave de dispositivo para continuar",
    macAddressLabel: "Dirección MAC",
    macAddressPlaceholder: "Introduce tu dirección MAC",
    deviceKeyLabel: "Clave del dispositivo",
    deviceKeyPlaceholder: "Introduce tu clave de dispositivo",
    loginInfoText:
      "Tu dirección MAC y clave del dispositivo se pueden encontrar en los ajustes de tu app. Si necesitas ayuda, por favor contacta con soporte.",
    loginFailedMessage:
      "Error de inicio de sesión. Por favor, inténtalo de nuevo.",
    whoWeAreTitle: "Quiénes somos",
    whoWeAreText1: "Somos",
    whoWeAreText2: "Intertament",
    whoWeAreText3:
      ", una empresa que ofrece una aplicación de streaming de nueva generación que redefine la simplicidad.",
    whoWeAreText4:
      "Nuestra plataforma se concentra en lo que realmente importa — una experiencia limpia y fluida que funciona con completa eficiencia.",
    whoWeAreText5: "Sin desorden. Sin distracciones.",
    whoWeAreText6:
      "Solo rendimiento inteligente y rápido impulsado por IA, junto con soporte empresarial y herramientas de desarrollo para revendedores y profesionales de la industria.",
    visionTitle: "Nuestra visión",
    visionText: "Convertirnos en la plataforma más",
    visionTrusted: "fiable",
    visionUserFriendly: "fácil de usar",
    visionFutureReady: "preparada para el futuro",
    visionTextEnd: "del mundo.",
    visionTrustedLabel: "Fiabilidad",
    visionUserFriendlyLabel: "Facilidad de uso",
    visionFutureReadyLabel: "Preparada para el futuro",
    missionTitle: "Nuestra misión",
    missionText1: "Proporcionar a los usuarios una experiencia de streaming",
    missionText1Highlight: "fluida, continua e innovadora",
    missionText1End: "",
    missionText2: "Ofrecer a los revendedores una",
    missionText2Highlight: "plataforma de gestión eficiente",
    missionText2End: "y soporte para el crecimiento",
    valuesTitle: "Nuestros valores",
    valuesSubtitle: "Los principios que guían todo lo que hacemos",
    valuesSimplicity: "Simplicidad",
    valuesSimplicityDesc: "Diseño limpio e intuitivo que cualquiera puede usar",
    valuesTrust: "Confianza",
    valuesTrustDesc: "Plataforma fiable y segura en la que puedes confiar",
    valuesInnovation: "Innovación",
    valuesInnovationDesc: "Tecnología IA de vanguardia para el futuro",
    valuesComfort: "Comodidad",
    valuesComfortDesc: "Experiencia fluida diseñada para tu comodidad",
    valuesTransparency: "Transparencia",
    valuesTransparencyDesc: "Abiertos y honestos en todo lo que hacemos",
    valuesSupport: "Soporte",
    valuesSupportDesc: "Asistencia 24/7 siempre que nos necesites",
    featuresTitle: "Características del reproductor",
    featuresSubtitle:
      "Todo lo que necesitas para la experiencia de streaming perfecta",
    featuresModernDesign: "Diseño moderno y limpio",
    featuresModernDesignDesc:
      "Una interfaz ligera, agradable a la vista que pone el contenido primero",
    featuresInstantAccess: "Acceso instantáneo",
    featuresInstantAccessDesc:
      "Entra al servidor y comienza a ver de inmediato",
    featuresSecureStable: "Seguro y estable",
    featuresSecureStableDesc:
      "Diseñado para máximo rendimiento, protección y velocidad",
    featuresInteractiveIntelligence: "Inteligencia interactiva",
    featuresInteractiveIntelligenceDesc:
      "Aprende de tu uso para recomendar el mejor contenido impulsado por IA",
    featuresSmartSearch: "Buscador inteligente",
    featuresSmartSearchDesc:
      "Descubrimiento de contenido rápido, intuitivo e inteligente",
    howItWorksTitle: "Cómo funciona",
    howItWorksSubtitle: "Comienza en solo 3 pasos sencillos",
    howItWorksStep1Title: "Descargar e instalar",
    howItWorksStep1Desc:
      "Busca Servo Player en la tienda de tu dispositivo e instálalo.",
    howItWorksStep1Note: "Actualmente disponible en Samsung y LG",
    howItWorksStep1ComingSoon:
      "Próximamente en Android TV, iOS, Toku, Windows y Apple TV",
    howItWorksStep2Title: "Introduce tus credenciales",
    howItWorksStep2Desc:
      "Introduce tu URL de servidor o código de activación mediante el sitio web.",
    howItWorksStep3Title: "Disfruta el streaming",
    howItWorksStep3Desc:
      "Deja que nuestra IA mejore tu experiencia y disfruta de un streaming fluido.",
    howItWorksAvailablePlatforms: "Plataformas disponibles",
    howItWorksComingSoon: "Próximamente",
    whyChooseUsTitle: "Por qué elegir ser revendedor con nosotros",
    whyChooseUsSubtitle:
      "Asóciate con Servo hoy y disfruta la experiencia de streaming del futuro",
    whyChooseUsFullControl: "Control total",
    whyChooseUsFullControlDesc:
      "Control total sobre tus clientes a través de un panel profesional",
    whyChooseUsSupport: "Soporte técnico 24/7",
    whyChooseUsSupportDesc: "Asistencia permanente siempre que la necesites",
    whyChooseUsPricing: "Precios competitivos",
    whyChooseUsPricingDesc:
      "Excelente relación calidad-precio con tarifas mayoristas",
    whyChooseUsOffers: "Ofertas exclusivas",
    whyChooseUsOffersDesc:
      "Paquetes y promociones especiales para nuestros revendedores",
    whyChooseUsTrusted: "Plataforma de confianza",
    whyChooseUsTrustedDesc:
      "Una plataforma moderna y de confianza impulsada por IA — querida por los clientes",
    whyChooseUsManagement: "Gestión centralizada",
    whyChooseUsManagementDesc:
      "Controla todos los usuarios, dispositivos y suscripciones en un solo lugar",
    whyChooseUsPerformance: "Rendimiento fiable",
    whyChooseUsPerformanceDesc:
      "Despídete de los tiempos de inactividad e inestabilidad — Servo ofrece rendimiento constante y fluido 24/7",
    whyChooseUsPartnership:
      "👉 Asóciate con Servo hoy y ofrece a tus clientes la experiencia de streaming del futuro.",
    whyChooseUsStartPartnership: "Inicia tu asociación",
    contactTitle: "Contáctanos",
    contactSubtitle:
      "Para más información o consultas de negocio, no dudes en ponerte en contacto",
    contactGetInTouch: "Ponte en contacto",
    contactEmail: "Correo electrónico",
    contactSupport: "Soporte",
    contactSupportAvailable: "Disponible 24/7",
    contactResponseTime: "Tiempo de respuesta",
    contactResponseTimeValue: "Dentro de 24 horas",
    contactFollowUs: "Síguenos",
    contactName: "Nombre",
    contactNamePlaceholder: "Tu nombre",
    contactEmailPlaceholder: "tu@correo.com",
    contactSubject: "Asunto",
    contactSubjectPlaceholder: "¿Cómo podemos ayudarte?",
    contactMessage: "Mensaje",
    contactMessagePlaceholder: "Tu mensaje...",
    contactSendMessage: "Enviar mensaje",
  },
  pt: {
    FEELTHEFLOW: "SINTA O FLUXO",
    heroSubTitle: "Aplicativo de streaming de nova geração",
    heroText:
      "Redefinindo a simplicidade com uma experiência limpa e fluida que funciona com total eficiência. Sem bagunça. Sem distrações. Apenas desempenho inteligente e rápido alimentado por IA.",
    ManagePlaylistTitle: "Gerenciar lista de reprodução",
    LoginPlaylist: "Faça login para adicionar sua lista de reprodução",
    Login: "Entrar",
    home: "Início",
    WhoWeAre: "Quem somos",
    vision: "Visão",
    features: "Recursos",
    howitworks: "Como funciona",
    contact: "Contato",
    reseller: "Revendedor",
    WishTvWebsite:
      "Nossa plataforma é o hub de soluções de entretenimento, com uma extensa coleção de tecnologias de streaming e conteúdo cuidadosamente selecionado.",
    WishTvDevice:
      "Assista à Nova TV com estes dispositivos de streaming compatíveis",
    ActivateDeviceOne: "Ativar dispositivos",
    SwitchMac: "Trocar MAC",
    ParentPin: "PIN dos pais",
    AccountDetails: "Detalhes da conta",
    Logout: "Sair",
    WishTvAboutOne:
      "Nova TV é o media-player para TV mais avançado e fácil de usar.",
    WishTvAboutTwo:
      "Com Nova TV, você aproveita seus meios favoritos na sua smart TV.",
    MobileVersion: "Versão móvel de",
    Available: "está disponível",
    wishtvAppAboutThree:
      "Disponível para Android na Play Store e para iOS na App Store.",
    FAQsTitle: "Perguntas frequentes",
    answerOne:
      "A Nova TV contém canais? Onde posso obter uma lista de reprodução?",
    questionOne:
      "Não, o aplicativo Nova TV não inclui canais e nenhuma informação será fornecida sobre onde você pode obter canais ou pacotes de canais. Além disso, os desenvolvedores do aplicativo não são responsáveis pelo conteúdo carregado no Wish TV.",
    answerTwo: "Como posso me tornar um provedor certificado do Wish TV?",
    questionTwo:
      "Você pode se candidatar na plataforma Wish TV ou entrar em contato com a equipe de suporte para mais informações sobre como se tornar um provedor certificado.",
    answerThree: "Como posso me tornar um provedor certificado do Wish TV?",
    questionThree:
      "Se você experimentar uma tela de carregamento que nunca termina, por favor reinicie o app ou verifique sua conexão com a internet.",
    answerFour: "Como posso usar a Nova TV?",
    questionFour:
      "Nova TV é simples de usar. Baixe o app, entre com suas credenciais e comece a aproveitar seus meios favoritos.",
    answerFive: "Tendo dificuldade para encontrar nosso app nas lojas?",
    questionFive:
      "Se você tiver dificuldade em encontrar nosso app, por favor certifique-se de que está procurando na loja correta para o sistema operacional do seu dispositivo (Android ou iOS).",
    answerSix: "Meu endereço MAC mudou após eu trocar o tipo de conexão.",
    questionSix:
      "Se seu endereço MAC mudou após trocar tipos de conexão, talvez você precise contatar o suporte para assistência em atualizar suas credenciais.",
    SendMessage: "Envie-nos uma mensagem",
    ContactUs: "Fale conosco",
    FullName: "Nome completo",
    Email: "E-mail",
    Subject: "Assunto",
    YourMessage: "Digite sua mensagem...",
    SendMessageButton: "Enviar mensagem",
    About: "Sobre",
    aboutDesc:
      "Nova TV é um aplicativo player que permite assistir conteúdo de alta qualidade em todos os dispositivos, seja sua TV, celular ou caixa Android, independentemente da velocidade da internet que você tiver.",
    PoliciesConditions: "Políticas e Condições",
    TermsConditions: "Termos e Condições",
    PrivacyPolicy: "Política de Privacidade",
    footer: "Copyright © 2025 Nova TV",
    AddPlaylist: "Adicionar lista de reprodução",
    LoadingPlaylists: "Carregando listas de reprodução…",
    Playlist: "Lista de reprodução",
    Actions: "Ações",
    ActivateDevice: "Ativar dispositivo",
    Price: "Preço",
    PaymentMethod: "Método de pagamento",
    noteOne: "NOTA",
    noteDesc:
      "Nova TV não fornece conteúdo e é puramente um media-player. Para usar Wish TV você precisa enviar sua própria lista de reprodução. Se você não tiver uma lista de reprodução, não poderá usar o Player Wish. Nesse caso, não pague. Também não permitimos ativação para usuários que não têm lista de reprodução.",
    SwitchDevice: "Trocar MAC do dispositivo",
    MaxLength: "Tamanho máximo",
    newMacAddress: "Novo endereço MAC",
    transferMacAddress:
      "Transfira sua ativação e listas de reprodução para outro endereço MAC de dispositivo",
    noteTwo: "NOTA",
    noteDescTwo:
      "Suas informações de login de dispositivo, listas de reprodução e período de ativação serão transferidos para este novo endereço MAC do dispositivo. Seu dispositivo com o endereço MAC antigo não estará mais vinculado a esta conta.",
    Save: "Salvar",
    parentPinTitle: "PIN dos pais",
    resetParentPIN: "Redefinir PIN dos pais",
    newParentPin: "Novo PIN dos pais",
    noteThree: "NOTA",
    noteDescThree:
      "Se você esqueceu seu PIN dos pais no app, você pode alterá-lo aqui.",
    AccountDetailsTitle: "Detalhes da conta",
    Status: "Status",
    CreationDate: "Data de criação",
    ExpirationDate: "Data de expiração",
    AddPlaylistTitle: "Adicionar lista de reprodução",
    EditPlaylistTitle: "Editar lista de reprodução",
    PlaylistName: "Nome da lista de reprodução",
    EnterPlaylistName: "Digite o nome da lista de reprodução",
    PlaylistURL: "URL da lista de reprodução",
    EnterPlaylistURL: "Digite a URL da lista de reprodução",
    ProtectedPlaylist: "Lista de reprodução protegida",
    noteFour: "NOTA",
    noteDescFour:
      "Listas de reprodução protegidas não poderão ser visualizadas ou modificadas sem inserir um PIN.",
    Password: "Senha",
    EnterPassword: "Digite a senha",
    Cancel: "Cancelar",
    Saving: "Salvando…",
    UpdatePlaylist: "Atualizar lista de reprodução",
    ErrorMessageOne: "Ocorreu um erro",
    ErrorMessageTwo: "URL da lista de reprodução é obrigatório",
    ErrorMessageThree: "Senha é obrigatória para listas protegidas",
    EditErrorMessageOne: "Falha ao atualizar a lista de reprodução",
    EditErrorMessageTwo: "Erro ao atualizar a lista de reprodução:",
    EditErrorMessageThree: "Ocorreu um erro ao atualizar a lista de reprodução",
    SaveChanges: "Salvar alterações",
    AccountDetailstTitle: "Detalhes da conta",
    AddPlaylistOne: "Adicionar lista de reprodução",
    AddPlaylistTwo: "Adicionar lista de reprodução",
    Enterplaylistname: "Digite o nome da lista de reprodução",
    EnterplaylistURL: "Digite a URL da lista de reprodução",
    Enterpassword: "Digite a senha",
    EditPlaylist: "Editar lista de reprodução",
    PlaylistNameOne: "Nome da lista de reprodução",
    PlaylistURLOne: "URL da lista de reprodução",
    PasswordOne: "Senha",
    EnterpasswordOne: "Digite a senha",
    wishtvAboutone:
      "Nova TV é o media-player para TV mais avançado e fácil de usar.",
    wishtvAboutTwo:
      "Com Nova TV, você aproveitará seus meios favoritos na sua smart TV.",
    footerDescription:
      "Aplicativo de streaming de nova geração que redefine a simplicidade.",
    quickLinks: "Links rápidos",
    whoWeAre: "Quem somos",
    howItWorks: "Como funciona",
    becomeReseller: "Torne-se revendedor",
    support: "Suporte",
    contactUs: "Fale conosco",
    manageDevices: "Gerenciar dispositivos",
    faq: "FAQ",
    documentation: "Documentação",
    legal: "Legal",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    cookiePolicy: "Política de cookies",
    copyright: "© 2024 Intertament. Todos os direitos reservados.",
    poweredBy: "Desenvolvido por Servo IT",
    whatsappAccountName: "Servo Player",
    whatsappStatusMessage: "Normalmente responde dentro de 1 hora",
    whatsappChatMessage: "Olá! Como podemos ajudar você?",
    whatsappPlaceholder: "Contate-nos",
    loginDescription:
      "Insira seu endereço MAC e chave do dispositivo para continuar",
    macAddressLabel: "Endereço MAC",
    macAddressPlaceholder: "Insira seu endereço MAC",
    deviceKeyLabel: "Chave do dispositivo",
    deviceKeyPlaceholder: "Insira sua chave do dispositivo",
    loginInfoText:
      "Seu endereço MAC e chave do dispositivo podem ser encontrados nas configurações do app. Se você precisar de ajuda, por favor entre em contato com o suporte.",
    loginFailedMessage: "Falha no login. Por favor, tente novamente.",
    whoWeAreTitle: "Quem somos",
    whoWeAreText1: "Somos",
    whoWeAreText2: "Intertament",
    whoWeAreText3:
      ", uma empresa que oferece um aplicativo de streaming de nova geração que redefine a simplicidade.",
    whoWeAreText4:
      "Nossa plataforma foca no que realmente importa — uma experiência limpa e fluida que funciona com total eficiência.",
    whoWeAreText5: "Sem bagunça. Sem distrações.",
    whoWeAreText6:
      "Apenas desempenho inteligente e rápido alimentado por IA, junto com suporte de negócios e ferramentas de desenvolvimento para revendedores e profissionais da indústria.",
    visionTitle: "Nossa visão",
    visionText: "Tornar-nos a plataforma mais",
    visionTrusted: "confiável",
    visionUserFriendly: "fácil de usar",
    visionFutureReady: "preparada para o futuro",
    visionTextEnd: "do mundo.",
    visionTrustedLabel: "Confiável",
    visionUserFriendlyLabel: "Fácil de usar",
    visionFutureReadyLabel: "Preparada para o futuro",
    missionTitle: "Nossa missão",
    missionText1: "Proporcionar aos usuários uma experiência de streaming",
    missionText1Highlight: "fluida, contínua e inovadora",
    missionText1End: "",
    missionText2: "Oferecer aos revendedores uma",
    missionText2Highlight: "plataforma de gestão eficiente",
    missionText2End: " e suporte para crescimento",
    valuesTitle: "Nossos valores",
    valuesSubtitle: "Os princípios que guiam tudo o que fazemos",
    valuesSimplicity: "Simplicidade",
    valuesSimplicityDesc: "Design limpo e intuitivo que qualquer um pode usar",
    valuesTrust: "Confiança",
    valuesTrustDesc: "Plataforma confiável e segura na qual você pode confiar",
    valuesInnovation: "Inovação",
    valuesInnovationDesc: "Tecnologia de IA de ponta para o futuro",
    valuesComfort: "Conforto",
    valuesComfortDesc: "Experiência fluida projetada para sua facilidade",
    valuesTransparency: "Transparência",
    valuesTransparencyDesc: "Abertos e honestos em tudo o que fazemos",
    valuesSupport: "Suporte",
    valuesSupportDesc: "Assistência 24/7 sempre que você precisar",
    featuresTitle: "Recursos do player",
    featuresSubtitle:
      "Tudo o que você precisa para a experiência de streaming perfeita",
    featuresModernDesign: "Design moderno e limpo",
    featuresModernDesignDesc:
      "Uma interface leve, agradável aos olhos que coloca o conteúdo em primeiro lugar",
    featuresInstantAccess: "Acesso instantâneo",
    featuresInstantAccessDesc:
      "Entre no servidor e comece a assistir imediatamente",
    featuresSecureStable: "Seguro e estável",
    featuresSecureStableDesc:
      "Construído para máximo desempenho, proteção e velocidade",
    featuresInteractiveIntelligence: "Inteligência interativa",
    featuresInteractiveIntelligenceDesc:
      "Aprende com seu uso para recomendar o melhor conteúdo alimentado por IA",
    featuresSmartSearch: "Motor de busca inteligente",
    featuresSmartSearchDesc:
      "Descoberta de conteúdo rápida, intuitiva e inteligente",
    howItWorksTitle: "Como funciona",
    howItWorksSubtitle: "Comece em apenas 3 passos simples",
    howItWorksStep1Title: "Baixar e instalar",
    howItWorksStep1Desc:
      "Procure por Servo Player na loja do seu dispositivo e instale-o.",
    howItWorksStep1Note: "Atualmente disponível em Samsung e LG",
    howItWorksStep1ComingSoon:
      "Em breve no Android TV, iOS, Toku, Windows e Apple TV",
    howItWorksStep2Title: "Insira suas credenciais",
    howItWorksStep2Desc:
      "Insira sua URL de servidor ou código de ativação através do site.",
    howItWorksStep3Title: "Aproveite o streaming",
    howItWorksStep3Desc:
      "Deixe nossa IA melhorar sua experiência e aproveite um streaming fluido.",
    howItWorksAvailablePlatforms: "Plataformas disponíveis",
    howItWorksComingSoon: "Em breve",
    whyChooseUsTitle: "Por que escolher ser revendedor conosco",
    whyChooseUsSubtitle:
      "Associe-se à Servo hoje e aproveite a experiência de streaming do futuro",
    whyChooseUsFullControl: "Controle total",
    whyChooseUsFullControlDesc:
      "Controle total sobre seus clientes através de um painel profissional",
    whyChooseUsSupport: "Suporte técnico 24/7",
    whyChooseUsSupportDesc: "Assistência 24 horas sempre que você precisar",
    whyChooseUsPricing: "Preços competitivos",
    whyChooseUsPricingDesc:
      "Excelente relação custo-benefício com tarifas por atacado",
    whyChooseUsOffers: "Ofertas exclusivas",
    whyChooseUsOffersDesc:
      "Pacotes e promoções especiais para nossos revendedores",
    whyChooseUsTrusted: "Plataforma confiável",
    whyChooseUsTrustedDesc:
      "Uma plataforma moderna e confiável alimentada por IA — amada pelos clientes",
    whyChooseUsManagement: "Gestão centralizada",
    whyChooseUsManagementDesc:
      "Controle todos os usuários, dispositivos e assinaturas em um só lugar",
    whyChooseUsPerformance: "Desempenho confiável",
    whyChooseUsPerformanceDesc:
      "Diga adeus ao tempo de inatividade e instabilidade — a Servo oferece desempenho consistente e fluido 24/7",
    whyChooseUsPartnership:
      "👉 Associe-se à Servo hoje e ofereça aos seus clientes a experiência de streaming do futuro.",
    whyChooseUsStartPartnership: "Comece sua parceria",
    contactTitle: "Fale conosco",
    contactSubtitle:
      "Para mais informações ou consultas de negócios, não hesite em entrar em contato",
    contactGetInTouch: "Entre em contato",
    contactEmail: "E-mail",
    contactSupport: "Suporte",
    contactSupportAvailable: "Disponível 24/7",
    contactResponseTime: "Tempo de resposta",
    contactResponseTimeValue: "Dentro de 24 horas",
    contactFollowUs: "Siga-nos",
    contactName: "Nome",
    contactNamePlaceholder: "Seu nome",
    contactEmailPlaceholder: "seu@e-mail.com",
    contactSubject: "Assunto",
    contactSubjectPlaceholder: "Como podemos ajudar?",
    contactMessage: "Mensagem",
    contactMessagePlaceholder: "Sua mensagem...",
    contactSendMessage: "Enviar mensagem",
  },
};
